export { default as FormLogin } from './FormLogin/FormLogin';
export { default as InicioTable} from './Table/InicioTable'
export { default as CardRecepcionista} from './CardRecepcionista/CardRecepcionista'
export { default as CardUniones} from './CardUniones/CardUniones'
export { default as CardForm } from './CardForm/CardForm'
export { default as Form } from './Form/Form'
export { default as Searchbar } from './Searchbar/Searchbar'
export { default as TableRegistros } from './TableRegistros/TableRegistros'
export { default as TableRegistrosMobile } from './TableRegistros/TableRegistrosMobile'
export { default as HistoriaClinica } from './HistoriaClinica/HistoriaClinica'
export { default as SearchbarSola } from './Searchbar/SearchbarSola/SearchbarSola'
export { default as TablaPacientes } from './TablaPacientes/TablaPacientes'