export { default as FormLogin } from "./FormLogin/FormLogin";
export { default as InicioTable } from "./Table/InicioTable";
export { default as CardRecepcionista } from "./CardRecepcionista/CardRecepcionista";
export { default as CardUniones } from "./CardUniones/CardUniones";
export { default as CardForm } from "./CardForm/CardForm";
export { default as Form } from "./Form/Form";
export { default as FormEditMedic } from "./Form/FormEditMedic";
export { default as Searchbar } from "./Searchbar/Searchbar";
export { default as TableRegistros } from "./TableRegistros/TableRegistros";
export { default as TableRegistrosMobile } from "./TableRegistros/TableRegistrosMobile";
export { default as HistoriaClinica } from "./HistoriaClinica/HistoriaClinica";
export { default as SearchbarSola } from "./Searchbar/SearchbarSola/SearchbarSola";
export { default as TablaPacientes } from "./TablaPacientes/TablaPacientes";
export { default as TablaHistoriaClinica } from "./TablaHistoriaClinica/TablaHistoriaClinica";
export { default as TablaTurnosActivos } from "./TablaTurnosActivos/TablaTurnosActivos";
export { default as Dropdowns } from "./Dropdowns/Dropdowns";
export { default as DropdownsEspecialidades } from "./Dropdowns/Dropdownsespecialidades";
export { default as FormRecepcionista } from "./Form/FormRecepcionista";
export { default as TableRegistrosRecep } from "./TableRegistros/TableRegistrosRecep";
export { default as SearchbarRecepcionista } from "./Searchbar/SeachbarRecep";
export { default as FormEditRecep } from "./Form/FormEditRecep";
export { default as FormPaciente } from "./Form/FormPaciente";
export { default as ButtonSidebar } from "./Button/MyButton"
export { default as DropdownsTurn } from "./Dropdowns/DropdownsTurn";
export { default as CardPaciente } from "./CardUniones/CardPaciente"
export { default as DropdownsespecialidadesForm } from "./Dropdowns/DropdownsespecialidadesForm"