export { default as Login } from './Login/Login';
export { default as Home } from './home/Home';
export { default as PerfilMedico } from './PerfilMedico/PerfilMedico'
export { default as PerfilRecepcionista } from './PerfilRecepcionista/PerfilRecepcionista' 
export { default as PerfilPaciente } from './PerfilPaciente/PerfilPaciente'
export { default as RegistroMedico } from './RegistroMedico/RegistroMedico'
export { default as RegistroRecepcionista } from './RegistroRecepcionista/RegistroRecepcionista'
export { default as AgendaRecepcionista } from './AgendaRecepcionista/AgendaRecepcionista'
export { default as AgendaMedico } from './AgendaMedico/AgendaMedico'
export { default as HistorialClinica } from './HistorialClinica/HistorialClinica'
export { default as RegistroPaciente } from './RegistroPacientes/RegistroPaciente'
export { default as SeleccionTurno } from './SeleccionTurno/SeleccionTurno'